public class AccountClassRecordCreation {
    String name;
    string Site;
    integer Phone;
    boolean sPartner;
   void AccountClassRecordCreation(){
        String name;
        string Site;
        integer Phone;
        boolean sPartner;
    }
    void m1(){
        system.debug('name========='+name);
        system.debug('name========='+Site);
        system.debug('name========='+Phone);
    }
    
}